version: 2
updates:

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '03:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  commit-message:
    prefix: "deps(ci)"
