# Continuous integration on git.sr.ht
image: nixos/latest
environment:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    flake-registry = https://raw.githubusercontent.com/akirak/flake-pins/master/registry.json
sources:
  - https://git.sr.ht/~akirak/nix-config
tasks:
  - update: |
      cd nix-config
      nix flake update --commit-lock-file
      if ! git diff --cached --exit-code; then
         git switch -c update-flake-inputs
         git commit -m 'flake: Update flake inputs'
         git push --force-with-lease origin HEAD
      fi

  - build: |
      cd nix-config
      if [[ $(git symbolic-ref HEAD) = update-flake-inputs ]]; then
         nixos-rebuild dry-build --flake .#li
         nix build .#homeConfigurations.x86_64-linux."defaultUser@localhost".activation-script \
           --dry-run
      fi
