* Nix/NixOS Configuration Monorepo
[[https://akirak.cachix.org][file:https://img.shields.io/badge/cachix-akirak-blue.svg]]

This is a monorepo for my Nix configuration files.
** Features
- The entire =flake.nix= is organized using [[https://github.com/gytis-ivaskevicius/flake-utils-plus][flake-utils-plus]]
- Manage user preferences using [[https://github.com/nix-community/home-manager][home-manager]]
- Configure Emacs using [[https://github.com/akirak/emacs-twist][emacs-twist]] and each session is sandboxed using [[https://github.com/containers/bubblewrap][bubblewrap]]
** Usage
*** Trying out the Emacs configuration
Emacs with native compilation takes a lot of time to build, but I sometimes push the Emacs executable to cachix, so you may be able to use the binary cache:

#+begin_src sh
cachix use akirak
#+end_src

If you are using Linux with Nix 2.4 installed, you can try out a sandboxed Emacs session:

#+begin_src sh
nix run github:akirak/nix-config#emacs -- ~/work/
#+end_src

The argument after =--= can be any existing file or directory on your file system.
The first argument is bind-mounted inside the sandbox, and the other directories in your home directory becomes invisible.
Network access is also forbidden.
