* Nix/NixOS Configuration Monorepo
[[https://akirak.cachix.org][file:https://img.shields.io/badge/cachix-akirak-blue.svg]]

This is a monorepo for my Nix configuration files.
** Features
- The entire =flake.nix= is organized using [[https://github.com/gytis-ivaskevicius/flake-utils-plus][flake-utils-plus]]
- Manage user preferences using [[https://github.com/nix-community/home-manager][home-manager]]
- Configure Emacs using [[https://github.com/akirak/emacs-twist][emacs-twist]] and each session is sandboxed using [[https://github.com/containers/bubblewrap][bubblewrap]]
** Usage
*** Trying out the Emacs configuration
If you are using Linux with Nix 2.4 installed, you can try out the configuration inside a sandbox session.
If you are worried, you can verify the bubblewrap options of [[file:sandbox/emacs.nix][the sandbox]].

This configuration uses an Emacs binary with native compilation (a.k.a. GccEmacs) enabled.
While it should take a lot of time to build GccEmacs, I push the Emacs binary to Cachix, so you will only build packages.

#+begin_src sh
cachix use akirak
#+end_src

Because =~/.emacs.d= is bind-mounted inside the sandbox, you can use the configuration without installing it:

#+begin_src sh
nix run github:akirak/nix-config#emacs.basic -- ~/tmp/
#+end_src

The argument after =--= can be any existing file or directory on your file system.
The first argument is bind-mounted inside the sandbox, and the other directories in your home directory becomes invisible.
Network access is also forbidden.
