# -*- eval: (org-make-toc-mode t); -*-
* Emacs Configuration
:PROPERTIES:
:TOC:      :include descendants :depth 2
:END:
[[https://akirak.cachix.org][file:https://img.shields.io/badge/cachix-akirak-blue.svg]]

[[https://flakehub.com/flake/akirak/emacs-config][file:https://img.shields.io/endpoint?url=https://flakehub.com/f/akirak/emacs-config/badge]]

This repository contains my Emacs configuration which is built using [[https://github.com/akirak/emacs-twist][emacs-twist]].
I use home-manager to install the configuration.

It is an org-babel configuration defined within [[file:emacs/emacs-config.org][a single file]].

Note: This configuration is currently built and tested only on Linux.
** Trying out
:PROPERTIES:
:ID:       3cc635d1-7bad-4d28-946e-e204b04aafaa
:END:
If you have Nix 2.9+ installed, you can try out the Emacs configuration without installing it.

There are two variants of the configuration.
One is built with the pgtk version of Emacs, which runs on Wayland:

#+begin_src bash
   nix run github:akirak/emacs-config#default-pgtk.wrappers.tmpdir
#+end_src

There is another version, an X11 variant, which is now discouraged:

#+begin_src bash
   nix run github:akirak/emacs-config#default-x11.wrappers.tmpdir
#+end_src

Both commands create a temporary directory which will be used as ~user-emacs-directory~ containing an init file.
The temporary directory will be cleaned up when Emacs exits.
