name: Build Emacs packages

on:
  push:
    paths:
    - 'emacs/**'
    - 'flake.*'
    branches-ignore:
    - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deps-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - run: nix build .#emacs-config.depsCheck --print-build-logs

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@V27
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v15
      with:
        name: akirak
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # The build script contains cachix integration.
        skipPush: true

    - name: Build packages
      run: nix run .#build-packages
      env:
        CACHIX_NAME: akirak
