name: Build Emacs packages

on:
  push:
    paths:
    - 'emacs/lock/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: '-source$'

    - run: nix build .#emacs-config.depsCheck --print-build-logs

    - run: nix build .#emacs-config --print-build-logs
