name: Build Emacs packages

on:
  push:
    paths:
    - 'emacs/**'
    - 'flake.*'
    branches-ignore:
    - master
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deps-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - run: nix build .#emacs-config.depsCheck --print-build-logs

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@V28
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    # nix-fast-build may not utilize substituters configured in the flake,
    # so run `nix build` to prefetch dependencies beforehand.
    - name: Prefetch dependencies
      run: nix build .#emacs-config.emacs --accept-flake-config --no-link

    - name: Build packages
      run: nix build .#emacs-config -L
    #   run: |
    #     nix run .#nix-fast-build -- \
    #       --flake "#packages.x86_64-linux.emacs-config.elispPackages" \
    #       --no-nom \
    #       --skip-cached \
    #       --no-link \
    #       --option accept-flake-config true \
    #       --cachix-cache akirak
    #   env:
    #     CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_AUTH_TOKEN }}'
