name: Check

on:
  pull_request:
    paths-ignore:
    - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        upstream-cache: https://akirak.cachix.org

    - uses: cachix/cachix-action@v12
      with:
        name: akirak
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: '-source$'

    - run: nix flake check
