name: Trigger rebuild and deploy

on:
  push:
    branches:
    - develop

jobs:
  dispatch:
    strategy:
      matrix:
        repo:
        - akirak/homelab
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.repo }}
          event-type: deploy
