name: Post-merge tasks

on:
  pull_request:
    types:
    - closed

jobs:
  tag-release:
    if: |
      github.event.pull_request.merged == true &&
      github.base_ref == 'master' &&
      github.head_ref == 'develop' &&
      github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id
    uses: ./.github/workflows/tag-release.yml
    with:
      ref: 'master'
    secrets: inherit

  recreate_develop:
    # Use the same condition as tag-release
    if: |
      github.event.pull_request.merged == true &&
      github.base_ref == 'master' &&
      github.head_ref == 'develop' &&
      github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - run: git switch -c develop HEAD
    # The develop branch should be deleted already. You can turn on
    # "Automatically delete head branches" in the general per-repository
    # settings to ensure this.
    - run: git push origin HEAD

  update_packages:
    needs: recreate_develop
    uses: ./.github/workflows/update-elisp.yml
    secrets: inherit
