name: Post-merge tasks

on:
  pull_request:
    types:
    - closed

jobs:
  update_develop:
    if: |
      github.event.pull_request.merged == true &&
      github.base_ref == 'master' &&
      github.head_ref == 'develop' &&
      github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - run: git switch -c develop HEAD
    - run: git push origin HEAD --force-with-lease

  update_packages:
    needs: update_develop
    uses: ./.github/workflows/update-elisp.yml
    secrets: inherit
