name: Tag a release

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions: {}

jobs:
  tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      release-tag: ${{ steps.tag.outputs.release_tag }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false

      - name: Tag the current head
        id: tag
        run: |
          tag="r$(date -d "$(git log -1 --format=%ci)" +%Y%m%d)"
          echo "release_tag=$tag" >> "$GITHUB_OUTPUT"
          git tag -f "$tag"
          git push --force origin "tags/$tag"

  release:
    needs: tag
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      release-tag: ${{ needs.tag.outputs.release-tag }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
