name: "Update other repositories"

on:
  pull_request:
    types:
      - closed

jobs:
  downstream-flakes:
    if: |
      github.event.pull_request.merged == true &&
      github.base_ref == 'develop' &&
      github.head_ref == 'update/flake-lock' &&
      github.event.pull_request.head.repo.id == github.event.pull_request.base.repo.id
    strategy:
      matrix:
        repo:
        - akirak/homelab
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ matrix.repo }}
          event-type: flake-update
