name: Update the flake from the registry

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - flake-update
  workflow_call:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PR_APP_ID }}
          private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: develop
          persist-credentials: false

      - name: Set up Nix
        uses: ./.github/actions/setup
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock files
        run: nix develop -c just update-flakes

      - name: Update the lock entries
        run: |
          nix run .#lock --impure
          nix run .#update --impure

      - uses: peter-evans/create-pull-request@b99c9ae23bcf83f0f5aa571c2f0093de8aa85036
        with:
          base: develop
          token: ${{ steps.generate-token.outputs.token }}
          title: 'deps: Update the root flake.lock'
          branch: bot/update/flake-lock
          labels: automation,update,emacs
