name: Update elisp

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 6'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        git config --add user.name 'github-actions[bot]'
        git config --add user.email '6270544+github-actions[bot]@users.noreply.github.com'
    - run: nix run .#update-elisp-lock
    - uses: peter-evans/create-pull-request@v4
      with:
        base: develop
        title: 'Update Emacs Lisp packages'
        branch: update/elisp-packages
        labels: automation,update,emacs
