name: Update the flake from the registry

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - flake-update
  workflow_call:

permissions:
  contents: read

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          app-id: ${{ secrets.CREATE_PR_APP_ID }}
          private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - uses: actions/checkout@v6
        with:
          ref: develop
          persist-credentials: false

      - name: Set up Nix
        uses: ./.github/actions/setup
        with:
          cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix flake update --inputs-from github:akirak/flake-pins

      - run: nix flake update --inputs-from github:akirak/flake-pins
        working-directory: partitions/checks

      - name: Update the lock entries
        run: |
          nix run .#lock --impure
          nix run .#update --impure

      - uses: peter-evans/create-pull-request@aa523f9db61947bd5e06efd77870ef065eae32cc
        with:
          base: develop
          token: ${{ steps.generate-token.outputs.token }}
          title: 'deps: Update the root flake.lock'
          branch: bot/update/flake-lock
          labels: automation,update,emacs
