name: Update Emacs Lisp package registries

on:
  schedule:
    - cron: '20 20 * * 5'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
    - uses: cachix/install-nix-action@31.3.0
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Update the registries
      run: nix flake update gnu-elpa nongnu-elpa melpa
    - name: Relock
      run: |
        nix run .#lock --impure
        nix run .#update --impure
    - uses: peter-evans/create-pull-request@v7
      with:
        base: develop
        token: ${{ secrets.PAT_FOR_PR }}
        title: 'deps: Update Emacs package registries'
        branch: bot/update/elpa
        labels: automation,update,emacs
