name: Update the flake from the registry

on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - flake-update
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
    - uses: cachix/install-nix-action@v26
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake update --inputs-from github:akirak/flake-pins
    - uses: peter-evans/create-pull-request@v6
      with:
        base: develop
        token: ${{ secrets.PAT_FOR_PR }}
        title: 'deps: Update the root flake.lock'
        branch: update/flake-lock
        labels: automation,update,emacs
