name: Update elisp

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: develop
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        git config --add user.name 'github-actions[bot]'
        git config --add user.email '6270544+github-actions[bot]@users.noreply.github.com'
    - run: git switch -C update/elisp-packages develop
    - run: |
        nix flake lock \
          --update-input melpa \
          --update-input gnu-elpa \
          --update-input epkgs
    - run: nix run .#lock --impure
    - run: nix run .#update --impure
    - run: nix run .#update-elisp-lock
    - run: git push origin HEAD --force
